name: Crowdin Action

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: crowdin action      
      uses: crowdin/github-action@1.0.10
      with:
        # upload sources option
        upload_sources: true

        # upload translations options
        upload_translations: true
        upload_language: 'zh'
        auto_approve_imported: true
        import_eq_suggestions: true

        # download translations options
        download_translations: true
        download_language: 'en'
        skip_untranslated_strings: true
        skip_untranslated_files: true
        export_only_approved: true
        push_translations: true
        commit_message: 'New Crowdin translations by Github Action'

        # This is the name of the git branch that Crowdin will create when opening a pull request.
        # This branch does NOT need to be manually created. It will be created automatically by the action.
        localization_branch_name: l10n_crowdin_action
        create_pull_request: true
        pull_request_title: 'New Crowdin translations'
        pull_request_body: 'New Crowdin pull request with translations'
        pull_request_labels: 'enhancement, good first issue'
        # This is the name of the git branch to with pull request will be created.
        # If not specified default repository branch will be used.
        pull_request_base_branch_name: not_default_branch

        # global options

        # This is the name of the top-level directory that Crowdin will use for files.
        # Note that this is not a "branch" in the git sense, but more like a top-level directory in your Crowdin project.
        # This branch does NOT need to be manually created. It will be created automatically by the action.
        crowdin_branch_name: l10n_branch
        config: 'crowdin.yml'
        dryrun_action: true

        # config options

        # This is a numeric id, not to be confused with Crowdin API v1 "project identifier" string
        # See "API v2" on https://crowdin.com/project/<your-project>/settings#api
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}

        # A personal access token, not to be confused with Crowdin API v1 "API key"
        # See https://crowdin.com/settings#api-key to generate a token
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
